### PR TITLE
do not cause compiliation error on uninitialized

### PR DESCRIPTION
**Pull request by acxz**
Solves #21043

### CODE REVIEW

**Review by khancyr — COMMENTED** [review]
Hello, 

This is the wrong way to solve the issue. You should initialize the variable and not remove the check.

If you don't initialize it, you will use it with random garbage you got on this memory pointer

**Comment by davidbuzz** [comment]
im with khancyr on this one, sorry will not accept.

**Comment by KrishnanS2006** [comment]
I'm not too sure how C++ and its compilation works, will ignoring an uninitialized error cause anything in the code to break? Any risks associated with using this patch?

**Comment by WickedShell** [comment]
I've been unable to find the appropriate patch to work around the problem with GCC 12.1 and uninitialized. The best I've found that I've done locally since I could show that the actual runtime didn't have a problem, but couldn't figure out how to resolve the warning was to push/pop an ignore around the constructor in AP_Soaring.

Just as a note though @khancyr and @davidbuzz master doesn't build with GCC 12.1 
```
../../libraries/AP_Soaring/AP_Soaring.cpp: In constructor ‘SoaringController::SoaringController(AP_TECS&, const AP_Vehicle::FixedWing&)’:
../../libraries/AP_Soaring/AP_Soaring.cpp:171:17: error: member ‘SoaringController::_polarParams’ is used uninitialized [-Werror=uninitialized]
  171 |     _speedToFly(_polarParams),
      |                 ^~~~~~~~~~~~
```

**Comment by khancyr** [comment]
@WickedShell I have make a pr to solve this. Reordering the initialization seems to be enough. Even if it looks a weak solution, it will be enough for now

**Comment by acxz** [comment]
Would using AP_Vector3f instead of the struct be a stronger solution?
