### PR TITLE
AP_Logger: correct coverage compilation

### PR DESCRIPTION
**Pull request by peterbarker**
Fixes:

```
[1103/1501] Compiling libraries/SITL/SIM_Parachute.cpp In file included from ../../libraries/AP_HAL/utility/sparse-endian.h:28,
                 from ../../libraries/AP_RCProtocol/AP_RCProtocol_Backend.h:24,
                 from ../../libraries/AP_RCProtocol/AP_RCProtocol.h:316,
                 from ../../libraries/AP_Logger/AP_Logger.h:16,
                 from ../../libraries/SITL/SIM_FlightAxis.cpp:33:
../../libraries/AP_Common/missing/byteswap.h:9:24: error: redefinition of ‘uint16_t __bswap_16(uint16_t)’
    9 | static inline uint16_t __bswap_16(uint16_t u)
      |                        ^~~~~~~~~~
compilation terminated due to -Wfatal-errors.

In file included from ../../libraries/AP_HAL/utility/sparse-endian.h:28,
                 from ../../libraries/AP_RCProtocol/AP_RCProtocol_Backend.h:24,
                 from ../../libraries/AP_RCProtocol/AP_RCProtocol.h:316,
                 from ../../libraries/AP_Logger/AP_Logger.h:16,
                 from ../../libraries/SITL/SIM_JSON.cpp:30:
../../libraries/AP_Common/missing/byteswap.h:9:24: error: redefinition of ‘uint16_t __bswap_16(uint16_t)’
    9 | static inline uint16_t __bswap_16(uint16_t u)
      |                        ^~~~~~~~~~
compilation terminated due to -Wfatal-errors.
```

Can be replicated with
`./Tools/autotest/autotest.py --debug --coverage build.unit_tests`

Introduced in https://github.com/ArduPilot/ardupilot/pull/31415 - that include really doesn't need to be in the header, originally the enumeration entry was protected with `#if`, I believe.

### CODE REVIEW

**Comment by peterbarker** [comment]
```
Board                    AP_Periph  antennatracker  blimp  bootloader  copter  heli  iofirmware  plane  rover  sub
CubeOrange-periph-heavy  *                                 *                                                   
Durandal                            *               *      *           *       *                 *      *      *
Hitec-Airspeed           *                                 *                                                   
KakuteH7-bdshot                     *               *      *           *       *                 *      *      *
MatekF405                           *               *      *           *       *                 *      *      *
Pixhawk1-1M-bdshot                  *               *                  *       *                 *      *      *
f103-QiotekPeriph        *                                 *                                                   
f303-Universal           *                                 *                                                   
iomcu                                                                                *                         
revo-mini                           *               *      *           *       *                 *      *      *
skyviper-v2450                                                         *                                       
```

**Comment by peterbarker** [comment]
> LGTM.
> 
> The situation with that byteswap file looks a bit weird and there's probably something underlying we're not doing right. There is a waf step to detect an "official" one and ours should be disabled in that case, that must not work properly with coverage.

I did try a `#pragma once` in there (as a second patch), but that was a long-shot.
