### PR TITLE
Fix compilation errors with gcc 6 (v2)

### PR DESCRIPTION
**Pull request by lucasdemarchi**
Alternative fixes to #4098 

@guludo please take a look. I didn't need the other patches to build with gcc 6.1.1 in archlinux.

### CODE REVIEW

**Comment by guludo** [comment]
Looks okay to me, thanks.

> I didn't need the other patches to build with gcc 6.1.1 in archlinux.

The patches regarding `abs()` function are needed for SITL. Did you try building for that?

**Comment by lucasdemarchi** [comment]
@guludo ok, taking that patch in as well.

Applied.
