### PR TITLE
Tools: Bring flake8 speed improvements to pre-commit

### PR DESCRIPTION
**Pull request by TunaLobster**
Bringing the same improvements added in #21035 to the pre-commit script.

Also I was thinking about the command line length limit. Hopefully by the time we get to close to that limit, the tag won't be necessary and the whole project will pass with `flake8 .` and the current .flake8 config file.

This commit did pass it's own check! (also shows it does work as a hook)
```
~/ardupilot$ git commit -m "Tools: Bring flake8 speed improvements to pre-commit"
***** Checking (Tools/gittools/pre-commit.py)
[pr/udpate-pre-commit dd08d5754c] Tools: Bring flake8 speed improvements to pre-commit
 1 file changed, 21 insertions(+), 16 deletions(-)
```

### CODE REVIEW

File: Tools/gittools/pre-commit.py [hunk 1]
```diff
@@ -18,24 +18,30 @@
...
-        pass
+        self.retcode = 0
+        self.files_to_check_flake8 = []
 
     def progress(self, message):
         print("***** %s" % (message, ))
 
-    def check_file(self, filepath):
+    @staticmethod
+    def check_for_flake8_tag(filepath):
```
Comment (peterbarker) [inline Tools/gittools/pre-commit.py:28]:
```suggestion
    def has_flake8_tag(filepath):
```

File: Tools/gittools/pre-commit.py [hunk 2]
```diff
@@ -75,10 +80,10 @@ def run(self):
                 # don't check deleted files
                 continue
             (base, extension) = os.path.splitext(filepath)
-            if extension != ".py":
-                continue
-            if not self.check_file(filepath):
-                self.retcode = 1
+            if extension == ".py" and self.check_for_flake8_tag(filepath):
+                self.files_to_check_flake8.append(filepath)
```
Comment (peterbarker) [inline Tools/gittools/pre-commit.py:84]: Why did you change this from doing the continue if it wasn't a file we're interested in?

```suggestion
            if extension != ".py":
                continue
            if not self.has_flake8_tag(filepath):
                continue
            self.files_to_check_flake8.append(filepath)
```

File: Tools/gittools/pre-commit.py [hunk 3]
```diff
@@ -75,10 +80,10 @@ def run(self):
...
+        if self.files_to_check_flake8:
+            self.check_flake8()
```
Comment (peterbarker) [inline Tools/gittools/pre-commit.py:86]: Is there some reason to keep the state persistently in self?  i.e. do `self.retcode` and `files_to_check_flake8` really need to be in `self`?

i.e. this could just be
```
        return self.run_flake8(files_to_check)
```

**Review by peterbarker — CHANGES_REQUESTED** [review]

File: Tools/gittools/pre-commit.py (hunk 3 above)
Comment (TunaLobster) [reply Tools/gittools/pre-commit.py:86]: No reason. More of a future thinking if more checks were added. Do all of the checks and then return from pre-commit.

File: Tools/gittools/pre-commit.py (hunk 2 above)
Comment (TunaLobster) [reply Tools/gittools/pre-commit.py:84]: Changing from a double negative to a single positive. The loop moves on in the same way. If other file format and their associated linters were to be added, the same pattern could be used.

File: Tools/gittools/pre-commit.py (hunk 1 above)
Comment (TunaLobster) [reply Tools/gittools/pre-commit.py:28]: Changed

**Comment by TunaLobster** [comment]
Created an example to show adding astyle to pre-commit.py and reusing the same patterns used here. https://github.com/TunaLobster/ardupilot/compare/pr/udpate-pre-commit...TunaLobster:ardupilot:pre/add-astyle-pre-commit

**Comment by TunaLobster** [comment]
@peterbarker Removed the class variables. Let me know what you think about this one and then maybe an astyle check can be added.

File: Tools/gittools/pre-commit.py [hunk 4]
```diff
@@ -15,27 +15,35 @@
...
-    def split_git_diff_output(self, output):
+    def check_flake8(self, files_to_check):
+        if files_to_check:
+            for path in files_to_check:
+                self.progress("Checking (%s)" % path)
+            ret = subprocess.run(["flake8"] + files_to_check,
+                                 stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
+            if ret.returncode != 0:
+                self.progress("Flake8 check failed: (%s)" % (ret.stdout))
+                return 1
```
Comment (peterbarker) [inline Tools/gittools/pre-commit.py:42]: These pytthon methods should be returning true or false, not a retcode.

File: Tools/gittools/pre-commit.py [hunk 5]
```diff
@@ -15,27 +15,35 @@
...
-        retcode = subprocess.call(["flake8", filepath])
-        if retcode != 0:
-            self.progress("File (%s) failed with retcode (%s)" %
-                          (filepath, retcode))
-            return False
-        return True
+        return False
 
-    def split_git_diff_output(self, output):
+    def check_flake8(self, files_to_check):
```
Comment (peterbarker) [inline Tools/gittools/pre-commit.py:34]:
```suggestion
    def files_are_flake8_clean(self, files_to_check):
```

File: Tools/gittools/pre-commit.py [hunk 6]
```diff
@@ -15,27 +15,35 @@
...
         pass
 
-    def progress(self, message):
+    @staticmethod
+    def progress(message):
         print("***** %s" % (message, ))
 
-    def check_file(self, filepath):
+    @staticmethod
+    def has_flake8_tag(filepath):
```
Comment (peterbarker) [inline Tools/gittools/pre-commit.py:28]: maybe just 
```
    return "AP_FLAKE8_CLEAN" in content
```
in here?

**Review by peterbarker — CHANGES_REQUESTED** [review]

File: Tools/gittools/pre-commit.py (hunk 4 above)
Comment (TunaLobster) [reply Tools/gittools/pre-commit.py]: Fixed. I think the return 1/0 at the end of run() is still needed. Clarity maybe in that case?

File: Tools/gittools/pre-commit.py (hunk 5 above)
Comment (TunaLobster) [reply Tools/gittools/pre-commit.py]: Fixed

File: Tools/gittools/pre-commit.py (hunk 6 above)
Comment (TunaLobster) [reply Tools/gittools/pre-commit.py:28]: Fixed

**Review by peterbarker — CHANGES_REQUESTED** [review]
Failed under Python2:
```
pbarker@fx:~/rc/ardupilot((HEAD detached from TunaLobster/pr/udpate-pre-commit))$ git commit -m "stuff" -a
***** Checking (Tools/autotest/autotest.py)
Traceback (most recent call last):
  File ".git/hooks/pre-commit", line 93, in <module>
    sys.exit(precommit.run())
  File ".git/hooks/pre-commit", line 86, in run
    if not self.files_are_flake8_clean(files_to_check_flake8):
  File ".git/hooks/pre-commit", line 36, in files_are_flake8_clean
    ret = subprocess.run(["flake8"] + files_to_check,
AttributeError: 'module' object has no attribute 'run'
pbarker@fx:~/rc/ardupilot((HEAD detached from TunaLobster/pr/udpate-pre-commit))$ 
```

**Comment by TunaLobster** [comment]
Working on python 2.7 and 3.8. Looks like check_output is still present in 3.11.0rc2 with no notes of being deprecated.

```
cpjohns@machine:~/ardupilot$ python2 Tools/gittools/pre-commit.py 
***** WARNING: (Tools/gittools/pre-commit.py) has unstaged changes
***** Checking (Tools/gittools/pre-commit.py)
***** Flake8 check failed: (Tools/gittools/pre-commit.py:34:40: W291 trailing whitespace
)
cpjohns@machine:~/ardupilot$ python2 Tools/gittools/pre-commit.py 
***** WARNING: (Tools/gittools/pre-commit.py) has unstaged changes
***** Checking (Tools/gittools/pre-commit.py)
cpjohns@machine:~/ardupilot$ python Tools/gittools/pre-commit.py 
***** WARNING: (Tools/gittools/pre-commit.py) has unstaged changes
***** Checking (Tools/gittools/pre-commit.py)
cpjohns@machine:~/ardupilot$ python Tools/gittools/pre-commit.py 
***** WARNING: (Tools/gittools/pre-commit.py) has unstaged changes
***** Checking (Tools/gittools/pre-commit.py)
***** Flake8 check failed: (b'Tools/gittools/pre-commit.py:34:40: W291 trailing whitespace\n')
```

**Comment by TunaLobster** [comment]
@peterbarker Bump for review?

**Review by peterbarker — APPROVED** [review]
LGTM

I've rebased this and will mark it MergeOnCIPass - thanks!

**Comment by peterbarker** [comment]
Merged, thanks!
