### ISSUE TITLE
Compilation broken for ChibiOS boards post-ChibiOS-upgrade

### ISSUE THREAD

**Issue by peterbarker** [ArduPilot/ardupilot#33172]
# Bug Report

### Issue details

Compilation of 3DR-L431-ASAUAV was broken by the recent upgrade to ChibiOS.

**Version**
master

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine
[ x ] AP_Periph

**Airframe type**
n/a

**Hardware type**
n/a

**Logs**

```
The first bad commit could be any of:
bb0b1f69bf8bbacb81c72e8eb4182e6337ada391
2c064ba9158caa0912eb389d6f2c525d65034b33
64913139b8cea5c2bf9b0f10eb3917a61544faca
4c5c889b3afd9262a61bcdf827a5cad9c530569c
We cannot bisect more!
```

```
[663/890] Compiling libraries/AP_HAL_ChibiOS/system.cpp
[858/890] Compiling Tools/AP_Periph/version.cpp
../../libraries/AP_HAL_ChibiOS/system.cpp:50:37: error: static assertion failed: unexpected STM32_HCLK value got ((((3998000U / 1) * 40) / 2) / 1U) expected 80000000
   50 | static_assert(HAL_EXPECTED_SYSCLOCK == STM32_HCLK, "unexpected STM32_HCLK value got " XSTR(STM32_HCLK) " expected " XSTR(HAL_EXPECTED_SYSCLOCK));
compilation terminated due to -Wfatal-errors.
```

**Comment by peterbarker** [comment]
This may be a second failure (`BotBloxDroneNet`?)

```
In file included from ../../modules/ChibiOS/os/hal/ports/STM32/STM32H7xx/stm32_isr.c:69:
../../modules/ChibiOS/os/hal/ports/STM32/LLD/FDCANv2/stm32_fdcan3.inc:42:2: error: #error "STM32_IRQ_FDCAN3_PRIORITY not defined in mcuconf.h"
   42 | #error "STM32_IRQ_FDCAN3_PRIORITY not defined in mcuconf.h"
```

**Comment by peterbarker** [comment]
Partially fixed by https://github.com/ArduPilot/ardupilot/pull/33323
