### PR TITLE
Use named float wrapper to fix GCC 8.1 compile error

### LINKED ISSUE #8353: SITL fail to compile with GCC 8.1
#### Issue details
SITL fail to compile with GCC 8.1
Works fine with clang 6.0.0

#### Version
5b56887428bd1cf300cbc9d2bc17cd1c6c1fb67c

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[ X ] Submarine

#### Logs
```
In function ‘void mav_array_memcpy(void*, const void*, size_t)’,
    inlined from ‘void mavlink_msg_named_value_float_send(mavlink_channel_t, uint32_t, const char*, float)’ at libraries/GCS_MAVLink/include/mavlink/v2.0/ardupilotmega/../common/./mavlink_msg_named_value_float.h:158:21,
    inlined from ‘void AP_Airspeed::read()’ at ../../libraries/AP_Airspeed/AP_Airspeed.cpp:404:43:
libraries/GCS_MAVLink/include/mavlink/v2.0/ardupilotmega/../protocol.h:176:9: error: ‘void* memcpy(void*, const void*, size_t)’ forming offset [5, 10] is out of the bounds [0, 4] [-Werror=array-bounds]
   memcpy(dest, src, n);
   ~~~~~~^~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1plus: some warnings being treated as errors

```
This issue was erroneous opened in mavlink https://github.com/mavlink/mavlink/issues/903.

### PR DESCRIPTION
**Pull request by WickedShell**
Fixes #8353 with a silly 10 byte name. Required to let GCC 8.1 work.

### CODE REVIEW

**Comment by magicrub** [comment]
Question, does C do the usual thing of appending a null char to that string? If so, does that make it 11 chars?

I imagine if you took a couple off then gcc gets mad, but does it also get mad if you have too many?

**Comment by WickedShell** [comment]
@patrickelectric it compiles for me with GCC 8.1, what compilier are you using?

**Comment by WickedShell** [comment]
@magicrub your right, it was appending a character, I've removed an unneeded one, and it doesn't care if there are to many. The complaint was memcpy'ing out of bounds from the string, if the string is larger then we copy it doesn't care.

**Comment by patrickelectric** [comment]
This same function is used in other places around the code.
```txt
ArduCopter/mode_flowhold.cpp:    mavlink_msg_named_value_float_send(MAVLINK_COMM_0, AP_HAL::millis(), "HEST", height_estimate);
ArduCopter/mode_flowhold.cpp:    mavlink_msg_named_value_float_send(MAVLINK_COMM_1, AP_HAL::millis(), "HEST", height_estimate);
ArduSub/GCS_Mavlink.cpp:    mavlink_msg_named_value_float_send(
ArduSub/GCS_Mavlink.cpp:    mavlink_msg_named_value_float_send(
ArduSub/GCS_Mavlink.cpp:    mavlink_msg_named_value_float_send(
ArduSub/GCS_Mavlink.cpp:    mavlink_msg_named_value_float_send(
ArduSub/GCS_Mavlink.cpp:    mavlink_msg_named_value_float_send(
ArduSub/GCS_Mavlink.cpp:    mavlink_msg_named_value_float_send(
ArduSub/GCS_Mavlink.cpp:    mavlink_msg_named_value_float_send(
```
Compiler:
```txt
gcc (GCC) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Output: https://paste.kde.org/pzlcyl37c

**Comment by WickedShell** [comment]
@patrickelectric Oh, that's the same class of issue, just affecting the other vehicles. (I was testing Plane here at the time), those vehicles would also need similar changes to resolve them.

**Comment by WickedShell** [comment]
Yes, but the magic one is something I'd call won't for airspeed.... Heck I
almost just used it as an excuse to cut the message until we get a proper
one :)

**Comment by WickedShell** [comment]
s/won't/wrong

File: libraries/GCS_MAVLink/GCS_Common.cpp [hunk 1]
```diff
@@ -1525,6 +1526,14 @@ void GCS_MAVLINK::send_vibration() const
         ins.get_accel_clip_count(2));
 }
 
+void GCS_MAVLINK::send_named_float(const char *name, float value) const
+{
+    char float_name[MAVLINK_MSG_NAMED_VALUE_FLOAT_FIELD_NAME_LEN+1] {};
```
Comment (OXINARF) [inline libraries/GCS_MAVLink/GCS_Common.cpp]: Why the +1? The char array needs exactly MAVLINK_MSG_NAMED_VALUE_FLOAT_FIELD_NAME_LEN. Contrary to vsnprintf, strncpy will copy every character until it can, it doesn't reserve space for null-terminator.

File: libraries/GCS_MAVLink/GCS_Common.cpp [hunk 2]
```diff
@@ -1525,6 +1526,14 @@ void GCS_MAVLINK::send_vibration() const
...
+    strncpy(float_name, name, MAVLINK_MSG_NAMED_VALUE_FLOAT_FIELD_NAME_LEN);
+    float_name[MAVLINK_MSG_NAMED_VALUE_FLOAT_FIELD_NAME_LEN] = 0;
```
Comment (OXINARF) [inline libraries/GCS_MAVLink/GCS_Common.cpp]: Again, why? This array position won't be read/copied by the MAVLink code.

**Comment by WickedShell** [comment]
Copter and Sub are both wrapped now, copter now sends to all active channels as well. I ran the behavior changes past tridge and randy on mumble and got affirmative opinions on the behavior change of sending to all channels as being correct.

File: libraries/GCS_MAVLink/GCS_Common.cpp (hunk 1 above)
Comment (OXINARF) [reply libraries/GCS_MAVLink/GCS_Common.cpp]: GCC 8.1 is killing me. Is it a compiler or a teaching tool? Gosh.

Anyway, rather than disabling the warning I'd prefer to use the strategy that GCC docs suggest (https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html): _To avoid the warning when the result is not expected to be NUL-terminated, call memcpy instead._

The incoming string has to be NUL-terminated, so doing a memcpy should always work, it either sends a NUL-terminated string smaller than the array size or it sends a not NUL-terminated string truncated to the array size.

**Comment by OXINARF** [comment]
Merged, thanks!
