### PR TITLE
AP_FlashIface: Fixed could be used unintialized

### PR DESCRIPTION
**Pull request by Jaaaky**

### CODE REVIEW

**Review by andyp1per — APPROVED** [review]

**Review by amilcarlucas — APPROVED** [review]

**Review by khancyr — APPROVED** [review]
I doubt it can used initialized as it settled at same time as erase_size and erase_size is checked for its init value that is 0.
Not a bad change thus

**Comment by Jaaaky** [comment]
> I doubt it can used initialized as it settled at same time as erase_size and erase_size is checked for its init value that is 0. Not a bad change thus

It's a compiler warning(error) for Line 699 if you try to build examples with O3.

```
../../libraries/AP_FlashIface/AP_FlashIface_JEDEC.cpp: In member function 'virtual bool AP_FlashIface_JEDEC::start_erase_offset(uint32_t, uint32_t, uint32_t&, uint32_t&, uint32_t&)':
../../libraries/AP_FlashIface/AP_FlashIface_JEDEC.cpp:703:18: error: 'ins' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  703 |     cmd.cmd   =  ins;
      |                  ^~~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
```

**Comment by Jaaaky** [comment]
Can you get this merged @khancyr ?

**Comment by khancyr** [comment]
Unfortunately, I cannot. But it is on the merge list now. If it don't pass until tomorrow, I will bother somebody to do it

**Comment by peterbarker** [comment]
@Jaaaky which compiler was producing this warning?

**Comment by Jaaaky** [comment]
@peterbarker  The compiler is gcc-arm-none-eabi-10-2020-q4-major 

Change O2 to O3 in libraries/AP_HAL_ChibiOS/hwdef/CubeBlack/hwdef.dat
Then run:
`git submodule update --init --recursive && ./waf configure --board=CubeBlack  && ./waf -p --target examples/location`

**Comment by peterbarker** [comment]
Makes no flash size difference on any board, so I'm merging this.

I'd be a bit leery of merging this for the scenario specified if it actually cost us bytes...
