### PR TITLE
ArduSub: fix build error in Guided_PosVel target accessor

### PR DESCRIPTION
**Pull request by tridge**
posvel_pos_target_cm was renamed to posvel_pos_target_neu_cm in #33425 
build broken by #33149

### CODE REVIEW

**Comment by Ryanf55** [comment]
The patch is not complete yet. Errors reported.
```
  ../../ArduSub/mode_guided.cpp: In member function 'bool ModeGuided::get_posvel_target_NEU_cm(Vector3f&) const':
  ../../ArduSub/mode_guided.cpp:307:11: error: 'posvel_pos_target_cm' was not declared in this scope; did you mean 'posvel_pos_target_neu_cm'?
    307 |     pos = posvel_pos_target_cm.tofloat();
        |           ^~~~~~~~~~~~~~~~~~~~
        |           posvel_pos_target_neu_cm
  compilation terminated due to -Wfatal-errors.
  ```

**Comment by tridge** [comment]
> The patch is not complete yet. Errors reported.

That is the build of master to do the size compare, the PR is complete but CI cannot pass due to the master build

**Review by Ryanf55 — APPROVED** [review]
