### ISSUE TITLE
fly_CopterAVC() got an unexpected keyword argument 'valgrind'

### ISSUE THREAD

**Issue by glody** [ArduPilot/ardupilot#4142]
#### Issue details
TypeError: fly_CopterAVC() got an unexpected keyword argument 'valgrind' while running fly.CopterAVC test
Pull request #4141 had created to fix this issue.

Git bisect result:
commit 8774f15b9a2c784d4095d93d7241994fac010dd0
Author: Peter Barker <pbarker@barker.dropbear.id.au>
Date:   Mon Apr 11 18:05:39 2016 +1000

    Tools: add valgrind option to autotest.py

:040000 040000 a111bc5b186c18d6c51db23f6f6b98cbe77feebd 609503f3b18df79cca47fac9d9bdf2194060c7e8 M      Tools

#### Version
_master branch:e3b2e90a2762684f240e481a285b46f6de0500ab_

#### Platform
- [ ] Copter

#### Airframe type
_NA_

#### Hardware type
_SITL_

#### Logs
FAILED STEP: fly.CopterAVC at Tue May 17 13:21:56 2016 (fly_CopterAVC() got an unexpected keyword argument 'valgrind')
Traceback (most recent call last):
File "./Tools/autotest/autotest.py", line 406, in run_tests
if not run_step(step):
File "./Tools/autotest/autotest.py", line 232, in run_step
return arducopter.fly_CopterAVC(viewerip=opts.viewerip, map=opts.map, valgrind=opts.valgrind)
TypeError: fly_CopterAVC() got an unexpected keyword argument 'valgrind'
('check step: ', 'fly.CopterAVC')
FAILED 1 tests: ['fly.CopterAVC']

**Comment by peterbarker** [comment]
Thanks!  We no longer get the problem in Python.  The test still doesn't pass for me due to an RC Calibration issue.
