### PR TITLE
AP_Hal: system: panic is WEAK, fixing MP SITL exe build

### PR DESCRIPTION
**Pull request by IamPete1**
This fixes the MP SITL build, it has been stuck since the 27th https://firmware.ardupilot.org/Tools/MissionPlanner/sitl/

Seems to have been broken by the changes to panic in https://github.com/ArduPilot/ardupilot/pull/18404

I was seeing this error:
```
lib/libAntennaTracker_libs.a(AP_InternalError.cpp.0.o):AP_InternalError.cpp:(.text$_ZN16AP_InternalError5errorENS_7error_tEt.part.1+0x30): undefined reference to `AP_HAL::panic(char const*, ...)'
lib/libAntennaTracker_libs.a(GCS_MAVLink.cpp.0.o):GCS_MAVLink.cpp:(.text$_mav_finalize_message_chan_send+0x331): undefined reference to `AP_HAL::panic(char const*, ...)'
lib/libAntennaTracker_libs.a(GCS_MAVLink.cpp.0.o):GCS_MAVLink.cpp:(.text$_mav_finalize_message_chan_send+0x415): undefined reference to `AP_HAL::panic(char const*, ...)'
lib/libAntennaTracker_libs.a(GCS_MAVLink.cpp.0.o):GCS_MAVLink.cpp:(.text$_mav_finalize_message_chan_send+0x467): undefined reference to `AP_HAL::panic(char const*, ...)'
lib/libAntennaTracker_libs.a(GCS_MAVLink.cpp.0.o):GCS_MAVLink.cpp:(.text$_mav_finalize_message_chan_send+0x47f): undefined reference to `AP_HAL::panic(char const*, ...)'
lib/libAntennaTracker_libs.a(GCS_MAVLink.cpp.0.o):GCS_MAVLink.cpp:(.text$_mavlink_resend_uart+0x1ae): more undefined references to `AP_HAL::panic(char const*, ...)' follow
collect2: error: ld returned 1 exit status
```

I'm not sure if this is the correct fix, but it does fix.

### CODE REVIEW

**Comment by TunaLobster** [comment]
CI is getting an error with cygwin on the last build for rover, but not failing. I think? Seems like the earlier builds in the log are working.

**Comment by hendjoshsr71** [comment]
Doh.  I'm just getting my cygwin to build for mission planner which I haven't but once a long time ago. 

I'm not sure if we want the function declaration to be declared WEAK for all HAL varieties? AKA HAL_CHIBOS I don't think we really want its functions to be able to be overriden by a strong symbol at link time. 
But I may be wrong. WEAK was a new concept for me  with this PR :)

This is dirty, but was my first successful thought that leaves HAL_CHIBIOS be. There is probably a better way I'm exploring currently. 

Of course with the below you couldn't run the unit tests successfully in Cygwin...
In AP_HAL_SITL
```cpp
#if defined(__CYGWIN__) || defined(__CYGWIN64__)
void panic(const char *errormsg, ...)
#else
void WEAK panic(const char *errormsg, ...)
#endif
```

**Comment by hendjoshsr71** [comment]
> CI is getting an error with cygwin on the last build for rover, but not failing. I think? Seems like the earlier builds in the log are working.

For the offending PR, the Cygwin Built test shows as successful, but if you look at the log it says build failed and shows this error.

**Comment by tridge** [comment]
just noticed this is a duplicate:
https://github.com/ArduPilot/ardupilot/pull/18827
