### PR TITLE
Use std::isnan and std::isinf to make things build on glibc >= 2.23

### PR DESCRIPTION
**Pull request by G33KatWork**
Building ArduPilot on Arch Linux failed with an error message like
>'isnan' was not declared in this scope

This is caused by a change in glibc >= 2.23

I replaced all calls to isinf and isnan with the C++ versions in the std namespace which fixed it.
Please see this glibc related bug for an explanation: https://sourceware.org/bugzilla/show_bug.cgi?id=19439

I tested the build of all projects under Linux, not on any embedded hardware, because I don't have any for testing right now, so please make sure it works on these targets as well before merging.

### CODE REVIEW

**Comment by OXINARF** [comment]
This is already fixed in master and your version would not work for PX4.

**Comment by G33KatWork** [comment]
I checked if master builds under Linux before creating the patch and this pull-request. It didn't.

**Comment by OXINARF** [comment]
Do you have your master up-to-date? This was fixed 3 days ago. What build system are you using, make or waf?

**Comment by G33KatWork** [comment]
Yes, I double checked. I'm on cc24f323d25439661429d9afe52cc41ab46741d1. I even did a clean checkout to make sure I didn't screw anything up with my patched.
I'm using make.

**Comment by OXINARF** [comment]
Can you post what error you get?

**Comment by G33KatWork** [comment]
Sure, here you go:

`$ make linux
make -C ArduPlane linux
make[1]: Entering directory '/home/andy/Desktop/dronecode/ardu2/ArduPlane'
Checking modules
// BUILDROOT=/tmp/ArduPlane.build HAL_BOARD=HAL_BOARD_LINUX HAL_BOARD_SUBTYPE=HAL_BOARD_SUBTYPE_LINUX_NONE TOOLCHAIN=NATIVE EXTRAFLAGS=-DGIT_VERSION="cc24f323" -I/home/andy/Desktop/dronecode/ardu2/libraries/AP_Common/missing -DHAVE_CMATH_ISFINITE -DNEED_CMATH_ISFINITE_STD_NAMESPACE
%% control_modes.o
In file included from /home/andy/Desktop/dronecode/ardu2/libraries/AP_Math/AP_Math.h:17:0,
                 from /home/andy/Desktop/dronecode/ardu2/libraries/AP_GPS/AP_GPS.h:22,
                 from Plane.h:42,
                 from control_modes.cpp:3:
/home/andy/Desktop/dronecode/ardu2/libraries/AP_Math/quaternion.h: In member function ‘bool Quaternion::is_nan() const’:
/home/andy/Desktop/dronecode/ardu2/libraries/AP_Math/quaternion.h:51:24: error: ‘isnan’ was not declared in this scope
         return isnan(q1) || isnan(q2) || isnan(q3) || isnan(q4);
                        ^
compilation terminated due to -Wfatal-errors.
../mk/build_rules.mk:11: recipe for target '/tmp/ArduPlane.build/control_modes.o' failed
make[1]: *** [/tmp/ArduPlane.build/control_modes.o] Error 1
make[1]: Leaving directory '/home/andy/Desktop/dronecode/ardu2/ArduPlane'
Makefile:18: recipe for target 'plane' failed
make: *** [plane] Error 2`

**Comment by OXINARF** [comment]
Ok, got it. Can you go to the file mk/board_native.mk and in line 6 add the following at the end of line: `-DHAVE_CMATH_ISINF -DNEED_CMATH_ISINF_STD_NAMESPACE -DHAVE_CMATH_ISNAN -DNEED_CMATH_ISNAN_STD_NAMESPACE` and try to compile again?

**Comment by G33KatWork** [comment]
Yep. That's it.
Thanks!

**Comment by OXINARF** [comment]
Ok, we probably need to fix this on master. @lucasdemarchi and @ricardotk can you guys take a look at this? I think that commit a0ca38a should have also declared the defines for `isinf` and `isnan` (and probably VRBrain shouldn't have declared nothing? I'm not familiar with that board but doesn't it use Nuttx too?)

**Comment by lucasdemarchi** [comment]
It's only fixed for waf. I don't think there's a reason anymore to use make for Linux boards. Could you try it?

**Comment by G33KatWork** [comment]
Using waf works fine.

**Comment by OXINARF** [comment]
@lucasdemarchi I think that it's great if we are ready to drop make for Linux boards but as long as we have it I think that most people will use it instead of waf. Let's hope we don't get many opened issues because of this.
